### ISSUE TITLE
Missing FA icons

### ISSUE THREAD

**Issue by ReDemoNBR** [jeselxe/tool-bar-atom#18]
The icons _level-up_, _level-down_ and _gear_ from FontAwesome are not available in **tool-bar** package.
The _level-up_ and _level-down_ icons are only available in PRO version of FontAwesome, which is not used in **tool-bar** package.

I suggest the following changes:
1. Change _level-up_ icon to _level-up-alt_ icon
2. Change _level-down_ icon to _level-down-alt_ icon
3. Change _gear_ icon to _cog_ icon

They are all available in free versions of FontAwesome

**Comment by jeselxe** [comment]
Better later than ever, PR accepted. Sorry for the delay, but I no longer use Atom, so it's difficult for me to spend time on it.
