### ISSUE TITLE
ToolBar isn't shown

### ISSUE THREAD

**Issue by idealtitude** [jeselxe/tool-bar-atom#6]
Hi,

first thanks for this nice package. A toolbar is something that is really missing in this nice software which is Atom.

I've installed your package but the toolbar appears nowhere... I've restarted Atom, but it doesn't change anything.

Is there something to do to make it appear, or is this a bug?

OS: Fedora 20

Thanks for your help!

**Comment by AlexNewson** [comment]
Have you got the base tool-bar package installed?

https://atom.io/packages/tool-bar

**Comment by idealtitude** [comment]
Thanks AlexNewson,

My bad, I missed the tool-bar package, that was the problem! And the real problem was that I didn't read the installation instructions...   :disappointed:
