### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList'

### ISSUE THREAD

**Issue by viki53** [jeselxe/tool-bar-atom#9]
Hi, I get the following error since I updated the `tool-bar` plugin and try to use this `tool-bar-atom` plugin:

```
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens
```

Looks like they did some changes and require you to update the plugin (see suda/tool-bar#148).

**Comment by ZeroCool2u** [comment]
The fix is to remove a space. 
It should be:
<code>    
@toolBar.addButton
      'icon': 'columns-fa-rotate-270'
      'iconset': 'fa'
      'tooltip': 'Split screen - Vertically'
      'callback': 'pane:split-down'
</code>

Not:
The fix is to remove a space between "columns" and "fa". This resolves the issue locally for me. 
It should be:
<code>    
@toolBar.addButton
      'icon': 'columns fa-rotate-270'
      'iconset': 'fa'
      'tooltip': 'Split screen - Vertically'
      'callback': 'pane:split-down'
</code>

**Comment by ZeroCool2u** [comment]
@jeselxe I've submitted a pull request. Let me know if this looks good to go. @viki53 You can fix this locally if you'd like by opening this file: /home/[USER NAME]/.atom/packages/tool-bar-atom/lib/tool-bar-atom.coffee in any text editor and replacing the space with a '-' as I described above. Note that the path I gave you is for a linux machine, so you'll need to find your config folder for atom if you're on Windows or Mac.

**Comment by jeselxe** [comment]
This fixes the issue, but removes the icon as the class 'columns-fa-rotate-270' doesn't exist.
There are two different classes to add, one for the columns and the other to rotate it in order to make it horizontal.
I'm trying to find a way to show it.

**Comment by jeselxe** [comment]
I have submitted a PR into the tool-bar to fix it. If it's accepted it should work.

**Comment by viki53** [comment]
It's already much better! Thanks!

There's indeed an icon missing for the split pane (vertically) button, but it's better than nothing

Appreciate it guys!

**Comment by ZeroCool2u** [comment]
@viki53 Yeah, it's not ideal, but better to lose a single button than the majority of functionality.

**Comment by jerone** [comment]
As I closed https://github.com/suda/tool-bar/pull/151 I'm proposing to use the following (untested) code in your situation:

```coffeescript
btn = @toolBar.addButton
  'icon': 'columns'
  'iconset': 'fa'
  'tooltip': 'Split screen - Vertically'
  'callback': 'pane:split-down'
btn.element.classList.add 'fa-rotate-270'
```

**Comment by jeselxe** [comment]
Nice, this works fine. Thanks
